In [1]:
import pandas as pd
import numpy as np

In [2]:
train_df = pd.read_csv(r'C:\Users\shash\Data\loan_data_train.csv')
test_df = pd.read_csv(r'C:\Users\shash\Data\loan_data_test.csv')

In [3]:
train_df.head()

,ID,Amount.Requested,Amount.Funded.By.Investors,Interest.Rate,Loan.Length,Loan.Purpose,Debt.To.Income.Ratio,State,Home.Ownership,Monthly.Income,FICO.Range,Open.CREDIT.Lines,Revolving.CREDIT.Balance,Inquiries.in.the.Last.6.Months,Employment.Length
0,79542.0,25000,25000,18.49%,60 months,debt_consolidation,27.56%,VA,MORTGAGE,8606.56,720-724,11,15210,3.0,5 years
1,75473.0,19750,19750,17.27%,60 months,debt_consolidation,13.39%,NY,MORTGAGE,6737.50,710-714,14,19070,3.0,4 years
2,67265.0,2100,2100,14.33%,36 months,major_purchase,3.50%,LA,OWN,1000.00,690-694,13,893,1.0,< 1 year
3,80167.0,28000,28000,16.29%,36 months,credit_card,19.62%,NV,MORTGAGE,7083.33,710-714,12,38194,1.0,10+ years
4,17240.0,24250,17431.82,12.23%,60 months,credit_card,23.79%,OH,MORTGAGE,5833.33,730-734,6,31061,2.0,10+ years

In [4]:
test_df.head()

,ID,Amount.Requested,Amount.Funded.By.Investors,Loan.Length,Loan.Purpose,Debt.To.Income.Ratio,State,Home.Ownership,Monthly.Income,FICO.Range,Open.CREDIT.Lines,Revolving.CREDIT.Balance,Inquiries.in.the.Last.6.Months,Employment.Length
0,20093,5000,5000,60 months,moving,12.59%,NY,RENT,4416.67,690-694,13,7686,0,< 1 year
1,62445,18000,18000,60 months,debt_consolidation,4.93%,CA,RENT,5258.50,710-714,6,11596,0,10+ years
2,65248,7200,7200,60 months,debt_consolidation,25.16%,LA,MORTGAGE,3750.00,750-754,13,7283,0,6 years
3,81822,7200,7200,36 months,debt_consolidation,17.27%,NY,MORTGAGE,3416.67,790-794,14,4838,0,10+ years
4,57923,22000,22000,60 months,debt_consolidation,18.28%,MI,MORTGAGE,6083.33,720-724,9,20181,0,8 years

In [5]:
# Combining test and training data for data preparation
test_df['Interest.Rate']=np.nan
train_df['data']='train'
test_df['data']='test'
test_df = test_df[train_df.columns]
final_df = pd.concat([train_df, test_df],axis=0)

In [6]:
final_df.head()

,ID,Amount.Requested,Amount.Funded.By.Investors,Interest.Rate,Loan.Length,Loan.Purpose,Debt.To.Income.Ratio,State,Home.Ownership,Monthly.Income,FICO.Range,Open.CREDIT.Lines,Revolving.CREDIT.Balance,Inquiries.in.the.Last.6.Months,Employment.Length,data
0,79542.0,25000,25000,18.49%,60 months,debt_consolidation,27.56%,VA,MORTGAGE,8606.56,720-724,11,15210,3.0,5 years,train
1,75473.0,19750,19750,17.27%,60 months,debt_consolidation,13.39%,NY,MORTGAGE,6737.50,710-714,14,19070,3.0,4 years,train
2,67265.0,2100,2100,14.33%,36 months,major_purchase,3.50%,LA,OWN,1000.00,690-694,13,893,1.0,< 1 year,train
3,80167.0,28000,28000,16.29%,36 months,credit_card,19.62%,NV,MORTGAGE,7083.33,710-714,12,38194,1.0,10+ years,train
4,17240.0,24250,17431.82,12.23%,60 months,credit_card,23.79%,OH,MORTGAGE,5833.33,730-734,6,31061,2.0,10+ years,train

In [7]:
final_df.dtypes

ID                                float64
Amount.Requested                   object
Amount.Funded.By.Investors         object
Interest.Rate                      object
Loan.Length                        object
Loan.Purpose                       object
Debt.To.Income.Ratio               object
State                              object
Home.Ownership                     object
Monthly.Income                    float64
FICO.Range                         object
Open.CREDIT.Lines                  object
Revolving.CREDIT.Balance           object
Inquiries.in.the.Last.6.Months    float64
Employment.Length                  object
data                               object
dtype: object

 Dropping cells ID and Amount.Funded.By.Investors as they are not valuable for the model.
 Cleaning Interest rate and debt to income by removing % and keeping the data type as numeric.
 Changing data type to numeric for : Amount.Requested , Open.CREDIT.Lines, Revolving.CREDIT.Balance 
 FICO.Range has interval value, will be keeping the average of intervals.
 Creating dummies for categorical variables Loan length, loan purpose, state and home ownership.

In [8]:
final_df.drop(['ID', 'Amount.Funded.By.Investors'], axis = 1, inplace = True)

In [9]:
for col in ['Interest.Rate','Debt.To.Income.Ratio']:
    final_df[col]=final_df[col].str.replace("%","")

In [10]:
for col in ['Amount.Requested', 'Interest.Rate','Debt.To.Income.Ratio',
            'Open.CREDIT.Lines','Revolving.CREDIT.Balance']:
    final_df[col]=pd.to_numeric(final_df[col],errors='coerce')

In [11]:
k=final_df['FICO.Range'].str.split("-",expand=True).astype(float)

final_df['FICO.Score']=0.5*(k[0]+k[1])

del final_df['FICO.Range']

final_df.head()

,Amount.Requested,Interest.Rate,Loan.Length,Loan.Purpose,Debt.To.Income.Ratio,State,Home.Ownership,Monthly.Income,Open.CREDIT.Lines,Revolving.CREDIT.Balance,Inquiries.in.the.Last.6.Months,Employment.Length,data,FICO.Score
0,25000.0,18.49,60 months,debt_consolidation,27.56,VA,MORTGAGE,8606.56,11.0,15210.0,3.0,5 years,train,722.0
1,19750.0,17.27,60 months,debt_consolidation,13.39,NY,MORTGAGE,6737.50,14.0,19070.0,3.0,4 years,train,712.0
2,2100.0,14.33,36 months,major_purchase,3.50,LA,OWN,1000.00,13.0,893.0,1.0,< 1 year,train,692.0
3,28000.0,16.29,36 months,credit_card,19.62,NV,MORTGAGE,7083.33,12.0,38194.0,1.0,10+ years,train,712.0
4,24250.0,12.23,60 months,credit_card,23.79,OH,MORTGAGE,5833.33,6.0,31061.0,2.0,10+ years,train,732.0

In [12]:
final_df['Employment.Length'].value_counts()

10+ years    653
< 1 year     249
2 years      243
3 years      235
5 years      202
4 years      191
1 year       177
6 years      163
7 years      127
8 years      108
9 years       72
.              2
Name: Employment.Length, dtype: int64

In [13]:
final_df['Employment.Length']=final_df['Employment.Length'].str.replace('years',"")

final_df['Employment.Length']=final_df['Employment.Length'].str.replace('year',"")

final_df['Employment.Length']=np.where(final_df['Employment.Length'].str[:2]=="10",10,final_df['Employment.Length'])

final_df['Employment.Length']=np.where(final_df['Employment.Length'].str[0]=="<",0,final_df['Employment.Length'])

final_df['Employment.Length']=pd.to_numeric(final_df['Employment.Length'],errors='coerce')

In [14]:
cat_col=final_df.select_dtypes(['object']).columns
cat_col

Index(['Loan.Length', 'Loan.Purpose', 'State', 'Home.Ownership', 'data'], dtype='object')

In [15]:
cat_col=cat_col[:-1]
cat_col

Index(['Loan.Length', 'Loan.Purpose', 'State', 'Home.Ownership'], dtype='object')

In [16]:
for col in cat_col:
    freqs=final_df[col].value_counts()
    k=freqs.index[freqs>20][:-1]
    for cat in k:
        name=col+'_'+cat
        final_df[name]=(final_df[col]==cat).astype(int)
    del final_df[col]
    print(col)

Loan.Length
Loan.Purpose
State
Home.Ownership

In [17]:
final_df.shape

(2500, 51)

In [18]:
final_df.isnull().sum()

Amount.Requested                     5
Interest.Rate                      300
Debt.To.Income.Ratio                 1
Monthly.Income                       3
Open.CREDIT.Lines                    9
Revolving.CREDIT.Balance             5
Inquiries.in.the.Last.6.Months       3
Employment.Length                   80
data                                 0
FICO.Score                           0
Loan.Length_36 months                0
Loan.Purpose_debt_consolidation      0
Loan.Purpose_credit_card             0
Loan.Purpose_other                   0
Loan.Purpose_home_improvement        0
Loan.Purpose_major_purchase          0
Loan.Purpose_small_business          0
Loan.Purpose_car                     0
Loan.Purpose_wedding                 0
Loan.Purpose_medical                 0
Loan.Purpose_moving                  0
State_CA                             0
State_NY                             0
State_TX                             0
State_FL                             0
State_IL                             0
State_GA                             0
State_PA                             0
State_NJ                             0
State_VA                             0
State_MA                             0
State_OH                             0
State_MD                             0
State_NC                             0
State_CO                             0
State_WA                             0
State_CT                             0
State_AZ                             0
State_MI                             0
State_AL                             0
State_MN                             0
State_MO                             0
State_NV                             0
State_OR                             0
State_SC                             0
State_WI                             0
State_KY                             0
State_LA                             0
State_KS                             0
Home.Ownership_MORTGAGE              0
Home.Ownership_RENT                  0
dtype: int64

In [19]:
for col in final_df.columns:
    if (col not in ['Interest.Rate','data'])& (final_df[col].isnull().sum()>0):
        final_df.loc[final_df[col].isnull(),col]=final_df.loc[final_df['data']=='train',col].mean()
        
final_df.isnull().sum()

Amount.Requested                     0
Interest.Rate                      300
Debt.To.Income.Ratio                 0
Monthly.Income                       0
Open.CREDIT.Lines                    0
Revolving.CREDIT.Balance             0
Inquiries.in.the.Last.6.Months       0
Employment.Length                    0
data                                 0
FICO.Score                           0
Loan.Length_36 months                0
Loan.Purpose_debt_consolidation      0
Loan.Purpose_credit_card             0
Loan.Purpose_other                   0
Loan.Purpose_home_improvement        0
Loan.Purpose_major_purchase          0
Loan.Purpose_small_business          0
Loan.Purpose_car                     0
Loan.Purpose_wedding                 0
Loan.Purpose_medical                 0
Loan.Purpose_moving                  0
State_CA                             0
State_NY                             0
State_TX                             0
State_FL                             0
State_IL                             0
State_GA                             0
State_PA                             0
State_NJ                             0
State_VA                             0
State_MA                             0
State_OH                             0
State_MD                             0
State_NC                             0
State_CO                             0
State_WA                             0
State_CT                             0
State_AZ                             0
State_MI                             0
State_AL                             0
State_MN                             0
State_MO                             0
State_NV                             0
State_OR                             0
State_SC                             0
State_WI                             0
State_KY                             0
State_LA                             0
State_KS                             0
Home.Ownership_MORTGAGE              0
Home.Ownership_RENT                  0
dtype: int64

In [20]:
#Splitting back the train and test data
train_df=final_df[final_df['data']=='train']
del train_df['data']
test_df=final_df[final_df['data']=='test']
test_df.drop(['Interest.Rate','data'],axis=1,inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:4102: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [21]:
del final_df

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
train1,train2=train_test_split(train_df,test_size=0.2,random_state=2)

In [24]:
x_train =train1.drop('Interest.Rate',axis=1)
y_train =train1['Interest.Rate']

# Linear Regression

In [25]:
from sklearn.metrics import r2_score

In [26]:
from sklearn.linear_model import LinearRegression

In [27]:
lr=LinearRegression()

In [28]:
lr.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [29]:
x_train.shape

(1760, 49)

In [30]:
lr.intercept_

75.9212141359478

In [31]:
list(zip(x_train.columns,lr.coef_))

[('Amount.Requested', 0.00015602405153877186),
 ('Debt.To.Income.Ratio', -0.003938504173777158),
 ('Monthly.Income', -2.6568573569170736e-05),
 ('Open.CREDIT.Lines', -0.039922608340240945),
 ('Revolving.CREDIT.Balance', -3.923647858838919e-06),
 ('Inquiries.in.the.Last.6.Months', 0.3361172111313311),
 ('Employment.Length', 0.0349936718945103),
 ('FICO.Score', -0.08667701121950822),
 ('Loan.Length_36 months', -3.143747246950592),
 ('Loan.Purpose_debt_consolidation', -0.46739356903559237),
 ('Loan.Purpose_credit_card', -0.6069873604061792),
 ('Loan.Purpose_other', 0.44417142270192733),
 ('Loan.Purpose_home_improvement', -0.3611899849181419),
 ('Loan.Purpose_major_purchase', -0.09589524932665638),
 ('Loan.Purpose_small_business', 0.06800548772823811),
 ('Loan.Purpose_car', 0.025259628036013893),
 ('Loan.Purpose_wedding', -0.779154265005644),
 ('Loan.Purpose_medical', -0.4281152109954953),
 ('Loan.Purpose_moving', 1.2845276544595716),
 ('State_CA', -0.21159715256759293),
 ('State_NY', -0.12777976346385944),
 ('State_TX', 0.4656519996969049),
 ('State_FL', 0.08536509194007688),
 ('State_IL', -0.6478521077890976),
 ('State_GA', -0.028715232683424435),
 ('State_PA', -0.5531491923550254),
 ('State_NJ', -0.4252715824292991),
 ('State_VA', -0.1900182794302424),
 ('State_MA', 0.09032034036316791),
 ('State_OH', -0.36139403402199943),
 ('State_MD', -0.0166147969097057),
 ('State_NC', -0.3012520492515626),
 ('State_CO', -0.05643938739112131),
 ('State_WA', -0.24431943682020324),
 ('State_CT', 0.4450659067910986),
 ('State_AZ', 0.2647218526843679),
 ('State_MI', -0.1581658355736979),
 ('State_AL', -0.32176623527151654),
 ('State_MN', -0.07658290397396375),
 ('State_MO', -0.4320941840325308),
 ('State_NV', -0.12433340941261034),
 ('State_OR', 0.1202482945947619),
 ('State_SC', 0.02477134526043881),
 ('State_WI', -0.16506920267021277),
 ('State_KY', 0.2692286032568502),
 ('State_LA', -0.0487968799518559),
 ('State_KS', 0.2442429179644846),
 ('Home.Ownership_MORTGAGE', -0.4927899396352776),
 ('Home.Ownership_RENT', -0.22835804629261117)]

In [32]:
x_train2=train2.drop('Interest.Rate',axis=1)

In [33]:
predicted_value = lr.predict(x_train2)

In [34]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import accuracy_score

In [35]:
mean_absolute_error(train2['Interest.Rate'],predicted_value)

1.6278267948887137

In [36]:
#carrying out the actual training and validation on test and train data
x_train=train_df.drop('Interest.Rate',axis=1)
y_train=train_df['Interest.Rate']

In [37]:
lr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [38]:
testDataPred_LinearReg = lr.predict(test_df)

In [39]:
r2_score(train2['Interest.Rate'],predicted_value)

0.7587856682638678

In [40]:
#writing the prediction to a file
pd.DataFrame(testDataPred_LinearReg).to_csv("Output_LinearReg.csv",index=False)

# Ridge Regression

In [41]:
from sklearn.linear_model import Ridge,Lasso
from sklearn.model_selection import GridSearchCV

In [42]:
lambdas=np.linspace(1,100,100)

In [43]:
ridge_param={'alpha':lambdas}

In [44]:
ridge_model=Ridge(fit_intercept=True)

In [45]:
grid_search=GridSearchCV(ridge_model,param_grid=ridge_param,cv=10,scoring='neg_mean_absolute_error')

In [46]:
grid_search.fit(x_train,y_train)

GridSearchCV(cv=10, error_score='raise-deprecating',
             estimator=Ridge(alpha=1.0, copy_X=True, fit_intercept=True,
                             max_iter=None, normalize=False, random_state=None,
                             solver='auto', tol=0.001),
             iid='warn', n_jobs=None,
             param_grid={'alpha': array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,...
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='neg_mean_absolute_error', verbose=0)

In [47]:
x_train2=train2.drop('Interest.Rate',axis=1)
predicted_value_RidgeReg = grid_search.predict(x_train2)
r2_score(train2['Interest.Rate'],predicted_value_RidgeReg)

0.7688453116561021

In [48]:
grid_search.best_estimator_

Ridge(alpha=34.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [49]:
grid_search.cv_results_

{'mean_fit_time': array([0.00956259, 0.00848281, 0.00895135, 0.00853801, 0.00847137,
        0.00941191, 0.00810595, 0.00898678, 0.00985782, 0.01015432,
        0.00994947, 0.00982044, 0.00710421, 0.0065892 , 0.00845342,
        0.00841804, 0.00887673, 0.00767105, 0.00706587, 0.00680032,
        0.00731699, 0.00776362, 0.00775449, 0.00778294, 0.00729871,
        0.00719624, 0.00573542, 0.00768809, 0.00736744, 0.00875933,
        0.00759923, 0.00715885, 0.00775683, 0.00851257, 0.00813015,
        0.0072027 , 0.00717127, 0.00843816, 0.00810354, 0.00753825,
        0.0111685 , 0.0099488 , 0.01135056, 0.01125121, 0.00953126,
        0.01020701, 0.01456277, 0.01220486, 0.01062956, 0.01085615,
        0.01055849, 0.01129856, 0.01205754, 0.01096065, 0.01032207,
        0.0113143 , 0.01177542, 0.00945294, 0.00773134, 0.00902932,
        0.00883541, 0.00773273, 0.00860231, 0.00774972, 0.00734921,
        0.00757101, 0.00756807, 0.00763881, 0.00629251, 0.00840948,
        0.00756485, 0.0085063 , 0.00805905, 0.00822196, 0.00628207,
        0.0064723 , 0.00753803, 0.00754747, 0.00883324, 0.00841002,
        0.00679038, 0.00717392, 0.00819561, 0.00765002, 0.00832069,
        0.00874312, 0.00763433, 0.007254  , 0.00651195, 0.00698488,
        0.00665164, 0.00829012, 0.0090142 , 0.00806134, 0.00744061,
        0.00820417, 0.0068656 , 0.00605099, 0.0074918 , 0.00703611]),
 'std_fit_time': array([0.00200616, 0.0010409 , 0.0019045 , 0.00181912, 0.00274528,
        0.00125243, 0.00315697, 0.00209432, 0.00151303, 0.00102385,
        0.00145949, 0.00156545, 0.00149403, 0.00068996, 0.00129585,
        0.00141761, 0.00129287, 0.00166687, 0.00175944, 0.00183442,
        0.00226241, 0.00133805, 0.0023247 , 0.00100481, 0.00140862,
        0.0016053 , 0.00188309, 0.00134588, 0.00100706, 0.00166731,
        0.00120088, 0.001651  , 0.0024938 , 0.00227842, 0.00037861,
        0.00160295, 0.00192669, 0.00123221, 0.00295675, 0.00197214,
        0.00167978, 0.00185137, 0.00151535, 0.00184961, 0.00144228,
        0.00287588, 0.00807795, 0.00228908, 0.00145896, 0.00236267,
        0.00161892, 0.00089308, 0.00249717, 0.00169576, 0.00228502,
        0.00216031, 0.00127342, 0.00285275, 0.00152894, 0.00177559,
        0.00103353, 0.00209072, 0.00168566, 0.00203894, 0.0011421 ,
        0.00232207, 0.00191329, 0.00164392, 0.00107399, 0.00155137,
        0.0012958 , 0.00167516, 0.00138932, 0.00132954, 0.00135866,
        0.00107638, 0.00266519, 0.00190839, 0.00280336, 0.00167014,
        0.00201601, 0.0013511 , 0.00135554, 0.00120706, 0.00149418,
        0.00156648, 0.00185974, 0.00144781, 0.00221643, 0.00105105,
        0.00167801, 0.0015372 , 0.00187005, 0.00174935, 0.00129555,
        0.00235545, 0.00130604, 0.00161831, 0.00194133, 0.0017489 ]),
 'mean_score_time': array([0.00231431, 0.00178027, 0.00209317, 0.00300155, 0.00221739,
        0.00337298, 0.00266089, 0.00299773, 0.00257616, 0.00264497,
        0.00318885, 0.00304368, 0.00272245, 0.0023972 , 0.00207589,
        0.00209045, 0.00131989, 0.00280044, 0.00216212, 0.00243371,
        0.00200367, 0.00240049, 0.00293813, 0.00200245, 0.00202403,
        0.00160055, 0.00285439, 0.0020076 , 0.00201666, 0.00287881,
        0.00160065, 0.00238197, 0.00131869, 0.00211046, 0.00160065,
        0.00172026, 0.00174346, 0.00242631, 0.0023999 , 0.00220811,
        0.00269897, 0.00552642, 0.00301361, 0.00266027, 0.00235336,
        0.00303514, 0.0026804 , 0.00329149, 0.00447729, 0.00326915,
        0.003303  , 0.00405431, 0.00291486, 0.00330591, 0.00257688,
        0.00323551, 0.00262203, 0.00212517, 0.00238345, 0.00225539,
        0.00276239, 0.00290749, 0.00173671, 0.0028358 , 0.00133173,
        0.00303645, 0.00163739, 0.0030828 , 0.00107322, 0.00310311,
        0.00207424, 0.00201242, 0.00227482, 0.00265   , 0.00248096,
        0.00262985, 0.0028801 , 0.00307531, 0.00197537, 0.0018435 ,
        0.00184948, 0.00309367, 0.00235326, 0.00214438, 0.00279918,
        0.00278494, 0.00167453, 0.00252347, 0.00209181, 0.00183444,
        0.00194981, 0.00181797, 0.00211122, 0.0022305 , 0.00278399,
        0.00285437, 0.00199192, 0.00171509, 0.00268807, 0.00292213]),
 'std_score_time': array([0.00202759, 0.00072321, 0.00170852, 0.00180135, 0.00160667,
        0.00124018, 0.00217103, 0.00155348, 0.00092443, 0.00071507,
        0.0009805 , 0.00157833, 0.00082773, 0.00126301, 0.00176641,
        0.00177131, 0.00182093, 0.00183332, 0.00218461, 0.00198961,
        0.00200369, 0.00196   , 0.00196525, 0.00200246, 0.00202476,
        0.00196027, 0.00187333, 0.00200772, 0.00123744, 0.0011374 ,
        0.00196038, 0.00194617, 0.00203719, 0.00193211, 0.00196038,
        0.00213135, 0.00217105, 0.00198243, 0.00195953, 0.00171598,
        0.00126347, 0.00089156, 0.00162463, 0.00183821, 0.00151738,
        0.00163366, 0.00167412, 0.00141688, 0.00090578, 0.00106319,
        0.00142639, 0.00104984, 0.00139718, 0.00106488, 0.00183543,
        0.00172229, 0.0010772 , 0.00110612, 0.00104986, 0.00199084,
        0.00154503, 0.00161472, 0.00179403, 0.0013546 , 0.00105348,
        0.00140452, 0.00105409, 0.00141799, 0.00103175, 0.002096  ,
        0.00165628, 0.00124438, 0.00166766, 0.00096827, 0.00121569,
        0.00089939, 0.00094022, 0.0015181 , 0.00155237, 0.00120338,
        0.00159198, 0.00073566, 0.00122051, 0.00078949, 0.00113581,
        0.00133017, 0.00138271, 0.00161273, 0.00195754, 0.0015804 ,
        0.00146873, 0.00129861, 0.00155452, 0.00146796, 0.00138094,
        0.00082132, 0.00126016, 0.00164901, 0.00113915, 0.00153245]),
 'param_alpha': masked_array(data=[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0,
                    11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0,
                    20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0,
                    29.0, 30.0, 31.0, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0,
                    38.0, 39.0, 40.0, 41.0, 42.0, 43.0, 44.0, 45.0, 46.0,
                    47.0, 48.0, 49.0, 50.0, 51.0, 52.0, 53.0, 54.0, 55.0,
                    56.0, 57.0, 58.0, 59.0, 60.0, 61.0, 62.0, 63.0, 64.0,
                    65.0, 66.0, 67.0, 68.0, 69.0, 70.0, 71.0, 72.0, 73.0,
                    74.0, 75.0, 76.0, 77.0, 78.0, 79.0, 80.0, 81.0, 82.0,
                    83.0, 84.0, 85.0, 86.0, 87.0, 88.0, 89.0, 90.0, 91.0,
                    92.0, 93.0, 94.0, 95.0, 96.0, 97.0, 98.0, 99.0, 100.0],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'alpha': 1.0},
  {'alpha': 2.0},
  {'alpha': 3.0},
  {'alpha': 4.0},
  {'alpha': 5.0},
  {'alpha': 6.0},
  {'alpha': 7.0},
  {'alpha': 8.0},
  {'alpha': 9.0},
  {'alpha': 10.0},
  {'alpha': 11.0},
  {'alpha': 12.0},
  {'alpha': 13.0},
  {'alpha': 14.0},
  {'alpha': 15.0},
  {'alpha': 16.0},
  {'alpha': 17.0},
  {'alpha': 18.0},
  {'alpha': 19.0},
  {'alpha': 20.0},
  {'alpha': 21.0},
  {'alpha': 22.0},
  {'alpha': 23.0},
  {'alpha': 24.0},
  {'alpha': 25.0},
  {'alpha': 26.0},
  {'alpha': 27.0},
  {'alpha': 28.0},
  {'alpha': 29.0},
  {'alpha': 30.0},
  {'alpha': 31.0},
  {'alpha': 32.0},
  {'alpha': 33.0},
  {'alpha': 34.0},
  {'alpha': 35.0},
  {'alpha': 36.0},
  {'alpha': 37.0},
  {'alpha': 38.0},
  {'alpha': 39.0},
  {'alpha': 40.0},
  {'alpha': 41.0},
  {'alpha': 42.0},
  {'alpha': 43.0},
  {'alpha': 44.0},
  {'alpha': 45.0},
  {'alpha': 46.0},
  {'alpha': 47.0},
  {'alpha': 48.0},
  {'alpha': 49.0},
  {'alpha': 50.0},
  {'alpha': 51.0},
  {'alpha': 52.0},
  {'alpha': 53.0},
  {'alpha': 54.0},
  {'alpha': 55.0},
  {'alpha': 56.0},
  {'alpha': 57.0},
  {'alpha': 58.0},
  {'alpha': 59.0},
  {'alpha': 60.0},
  {'alpha': 61.0},
  {'alpha': 62.0},
  {'alpha': 63.0},
  {'alpha': 64.0},
  {'alpha': 65.0},
  {'alpha': 66.0},
  {'alpha': 67.0},
  {'alpha': 68.0},
  {'alpha': 69.0},
  {'alpha': 70.0},
  {'alpha': 71.0},
  {'alpha': 72.0},
  {'alpha': 73.0},
  {'alpha': 74.0},
  {'alpha': 75.0},
  {'alpha': 76.0},
  {'alpha': 77.0},
  {'alpha': 78.0},
  {'alpha': 79.0},
  {'alpha': 80.0},
  {'alpha': 81.0},
  {'alpha': 82.0},
  {'alpha': 83.0},
  {'alpha': 84.0},
  {'alpha': 85.0},
  {'alpha': 86.0},
  {'alpha': 87.0},
  {'alpha': 88.0},
  {'alpha': 89.0},
  {'alpha': 90.0},
  {'alpha': 91.0},
  {'alpha': 92.0},
  {'alpha': 93.0},
  {'alpha': 94.0},
  {'alpha': 95.0},
  {'alpha': 96.0},
  {'alpha': 97.0},
  {'alpha': 98.0},
  {'alpha': 99.0},
  {'alpha': 100.0}],
 'split0_test_score': array([-1.72358138, -1.72420643, -1.72488332, -1.72551715, -1.72611705,
        -1.726689  , -1.72724387, -1.72782936, -1.72839732, -1.72896669,
        -1.72954587, -1.7301274 , -1.73070845, -1.73127717, -1.7318344 ,
        -1.7323809 , -1.73291734, -1.73344429, -1.7339623 , -1.73447182,
        -1.73497329, -1.73546709, -1.73595358, -1.73643308, -1.73690589,
        -1.73737227, -1.73783249, -1.73828676, -1.73873531, -1.73917834,
        -1.73961603, -1.74004856, -1.7405097 , -1.74104459, -1.74159538,
        -1.74214058, -1.74268031, -1.74321473, -1.74374395, -1.74432305,
        -1.74501456, -1.74570004, -1.7463796 , -1.74705336, -1.74772141,
        -1.74838387, -1.74904083, -1.74969239, -1.75035082, -1.75101435,
        -1.75167244, -1.7523252 , -1.75299962, -1.75367457, -1.75434372,
        -1.75500719, -1.75566506, -1.75631744, -1.75696443, -1.75760612,
        -1.7582426 , -1.75887395, -1.75950025, -1.7601216 , -1.760746  ,
        -1.76139675, -1.76204251, -1.76268335, -1.76331934, -1.76395894,
        -1.76460774, -1.76525171, -1.76589091, -1.76652542, -1.76715531,
        -1.76778063, -1.7684233 , -1.76906158, -1.76969529, -1.77032448,
        -1.77094921, -1.77156954, -1.77218554, -1.77279726, -1.77340474,
        -1.77400806, -1.77460725, -1.77520238, -1.77579348, -1.77638062,
        -1.77696383, -1.77754318, -1.77811869, -1.77869043, -1.77925842,
        -1.77982273, -1.78038338, -1.78094043, -1.78149391, -1.78204386]),
 'split1_test_score': array([-1.76219454, -1.75903763, -1.75623933, -1.75395455, -1.75197626,
        -1.75017074, -1.74845623, -1.746826  , -1.74527378, -1.74387719,
        -1.74258427, -1.74135105, -1.74017328, -1.73904709, -1.73796896,
        -1.73693568, -1.73594433, -1.73510332, -1.73429931, -1.73357746,
        -1.73289635, -1.73224239, -1.73161399, -1.73100966, -1.73042804,
        -1.72986788, -1.72932798, -1.72880728, -1.72830475, -1.72781947,
        -1.72735055, -1.72689718, -1.72645858, -1.72603406, -1.72564093,
        -1.72527274, -1.7249398 , -1.72461788, -1.72430649, -1.72400516,
        -1.72371345, -1.72343094, -1.72315723, -1.72289196, -1.72263477,
        -1.72238533, -1.72214332, -1.72190844, -1.72168042, -1.72145899,
        -1.72124388, -1.72103486, -1.7208317 , -1.72063418, -1.72044209,
        -1.72025524, -1.72007342, -1.71989647, -1.71972421, -1.71955648,
        -1.71939312, -1.71923399, -1.71907893, -1.71892781, -1.7187805 ,
        -1.71865008, -1.71853846, -1.71842992, -1.71832436, -1.71822169,
        -1.71812181, -1.71802463, -1.71793006, -1.71783802, -1.71774842,
        -1.71766119, -1.71757625, -1.71749353, -1.71741297, -1.71734177,
        -1.71730113, -1.71726236, -1.71722538, -1.71719015, -1.7171566 ,
        -1.71715105, -1.71719037, -1.71723934, -1.71728928, -1.71734015,
        -1.71739192, -1.71744454, -1.71749799, -1.71755222, -1.7176072 ,
        -1.71766291, -1.71771931, -1.71777637, -1.71786817, -1.71797334]),
 'split2_test_score': array([-1.77797477, -1.77545201, -1.77326532, -1.77140267, -1.76974652,
        -1.7682434 , -1.76692394, -1.76642358, -1.76597837, -1.76557934,
        -1.76521963, -1.76489384, -1.76459764, -1.76432751, -1.76408054,
        -1.76385429, -1.76364669, -1.76345597, -1.7632806 , -1.76311926,
        -1.76297077, -1.76283411, -1.76271385, -1.76263464, -1.76256404,
        -1.76250145, -1.76244628, -1.76239803, -1.76235624, -1.76232047,
        -1.76229035, -1.76226552, -1.76224565, -1.76223044, -1.76221961,
        -1.76221291, -1.7622101 , -1.76221095, -1.76221527, -1.76222286,
        -1.76223353, -1.76232306, -1.76248036, -1.76263832, -1.76279686,
        -1.76300679, -1.76324751, -1.76348786, -1.7637278 , -1.76397226,
        -1.76421705, -1.76446119, -1.76470463, -1.76494736, -1.76518935,
        -1.76543058, -1.76567103, -1.76591068, -1.76614951, -1.76639077,
        -1.76665418, -1.766939  , -1.76723854, -1.76753889, -1.76788217,
        -1.76824165, -1.76859917, -1.76895474, -1.76930837, -1.76966007,
        -1.77000984, -1.7703577 , -1.77070365, -1.77106568, -1.77143949,
        -1.77181079, -1.77217962, -1.77254599, -1.77290994, -1.7732715 ,
        -1.77363069, -1.77398755, -1.77434209, -1.77469435, -1.77504436,
        -1.77539213, -1.77573769, -1.77608108, -1.7764223 , -1.77676138,
        -1.77709836, -1.77743324, -1.77776606, -1.77809683, -1.77842557,
        -1.77875232, -1.77907708, -1.77939988, -1.77972074, -1.78003968]),
 'split3_test_score': array([-1.64840333, -1.64735435, -1.64655986, -1.64619483, -1.64586451,
        -1.64557283, -1.64530576, -1.64505448, -1.64481599, -1.64458809,
        -1.6444109 , -1.64426518, -1.64412587, -1.6439922 , -1.64386355,
        -1.64373941, -1.64361935, -1.64351967, -1.64342615, -1.64337521,
        -1.64332944, -1.64328551, -1.64324324, -1.6432025 , -1.64316317,
        -1.64312513, -1.64308829, -1.64305255, -1.64301784, -1.64298408,
        -1.64295121, -1.64291916, -1.64288789, -1.64285734, -1.64282747,
        -1.64279824, -1.64276961, -1.64274153, -1.64271398, -1.64268694,
        -1.64266329, -1.64265498, -1.6426481 , -1.64264165, -1.6426356 ,
        -1.64262993, -1.64262461, -1.64261964, -1.64261498, -1.64261062,
        -1.64262829, -1.64265714, -1.64268588, -1.6427145 , -1.642743  ,
        -1.64277136, -1.64279958, -1.64282766, -1.64285559, -1.64288337,
        -1.642911  , -1.64293848, -1.6429658 , -1.64302244, -1.64309874,
        -1.64318636, -1.64327337, -1.64335979, -1.64344562, -1.64353086,
        -1.64361551, -1.6436996 , -1.64378311, -1.64386605, -1.64394844,
        -1.64403028, -1.64411156, -1.64419231, -1.64428089, -1.64440206,
        -1.64452247, -1.64467497, -1.64483078, -1.64498848, -1.64514518,
        -1.64531965, -1.64551207, -1.64570335, -1.64590423, -1.6461169 ,
        -1.64632837, -1.64653867, -1.64674781, -1.64695578, -1.64716261,
        -1.64736831, -1.64757287, -1.64777632, -1.64797866, -1.6481799 ]),
 'split4_test_score': array([-1.4528175 , -1.45170879, -1.45056942, -1.44942369, -1.4482914 ,
        -1.44718246, -1.44610168, -1.44505108, -1.44403112, -1.44308012,
        -1.44218434, -1.44134568, -1.44053185, -1.43976574, -1.43906924,
        -1.43839255, -1.43773462, -1.43709499, -1.4364791 , -1.43587933,
        -1.43529483, -1.43472779, -1.43417625, -1.43363783, -1.43311916,
        -1.4326922 , -1.4322759 , -1.43187156, -1.43152853, -1.43120134,
        -1.43088216, -1.4305706 , -1.43031318, -1.43007317, -1.4298396 ,
        -1.42961217, -1.42939059, -1.4291746 , -1.42896395, -1.42877128,
        -1.42859544, -1.42842363, -1.42825568, -1.42809534, -1.42799323,
        -1.42792627, -1.4278619 , -1.42780001, -1.42774047, -1.4276832 ,
        -1.42762808, -1.42757502, -1.42752394, -1.42750299, -1.42749653,
        -1.42749132, -1.42748729, -1.42748441, -1.4274826 , -1.42748183,
        -1.42748203, -1.42748317, -1.42748521, -1.42748809, -1.42749178,
        -1.42749624, -1.42751485, -1.42754969, -1.427585  , -1.42762076,
        -1.42765694, -1.42769352, -1.42773047, -1.4277956 , -1.42789828,
        -1.42800197, -1.42810513, -1.42820775, -1.42830983, -1.42841139,
        -1.42851241, -1.42861291, -1.42871287, -1.42881231, -1.42891123,
        -1.42900963, -1.42910751, -1.42920487, -1.42930172, -1.42943034,
        -1.42956259, -1.42969413, -1.42982497, -1.4299551 , -1.43009326,
        -1.43024735, -1.43040057, -1.43055292, -1.4307044 , -1.43085502]),
 'split5_test_score': array([-1.64312555, -1.6422563 , -1.64139114, -1.64054028, -1.63970823,
        -1.6389013 , -1.63816312, -1.63744394, -1.63674337, -1.63606084,
        -1.63539564, -1.63474703, -1.63411429, -1.63349667, -1.63289348,
        -1.63230405, -1.63172777, -1.63116403, -1.63061388, -1.630076  ,
        -1.62954911, -1.62903278, -1.62852656, -1.62803006, -1.62754289,
        -1.6270647 , -1.62659516, -1.62613394, -1.62569538, -1.62528726,
        -1.62488729, -1.62449517, -1.62411061, -1.62373333, -1.6233631 ,
        -1.62299966, -1.62264279, -1.62229228, -1.6219479 , -1.62160947,
        -1.6212768 , -1.62094971, -1.62062803, -1.6203116 , -1.62003353,
        -1.61979199, -1.61957105, -1.6193757 , -1.61919222, -1.61901198,
        -1.61883488, -1.61866082, -1.61848971, -1.61832148, -1.61815604,
        -1.61801513, -1.61790803, -1.61780322, -1.61770062, -1.61760016,
        -1.61750178, -1.61740543, -1.61731104, -1.61721855, -1.61712792,
        -1.61703909, -1.61695201, -1.61686663, -1.61681129, -1.6167768 ,
        -1.61674361, -1.61671169, -1.61668101, -1.61665152, -1.61662319,
        -1.61659599, -1.61656988, -1.61655031, -1.61653605, -1.61652264,
        -1.61651005, -1.61649826, -1.61651822, -1.61655484, -1.61659176,
        -1.61662896, -1.61666642, -1.61670413, -1.61674209, -1.61678027,
        -1.61683026, -1.6168855 , -1.61694075, -1.61700291, -1.61709469,
        -1.61718624, -1.61727756, -1.61736863, -1.61745946, -1.61755005]),
 'split6_test_score': array([-1.43120121, -1.43020632, -1.4293075 , -1.42857716, -1.42804058,
        -1.42753515, -1.42705626, -1.42660047, -1.42616515, -1.42575528,
        -1.42542414, -1.42511808, -1.42488836, -1.42466955, -1.42446088,
        -1.42426167, -1.42407131, -1.42389157, -1.42374376, -1.42360284,
        -1.42348502, -1.42340271, -1.42335533, -1.4233135 , -1.42327694,
        -1.42324537, -1.42321854, -1.42319621, -1.42317816, -1.42316419,
        -1.4231541 , -1.42314772, -1.42314486, -1.42314537, -1.42314909,
        -1.42315588, -1.42316561, -1.42321615, -1.42327677, -1.42333941,
        -1.42340397, -1.42347037, -1.42354686, -1.42363182, -1.42371821,
        -1.42380596, -1.423895  , -1.42398527, -1.42407668, -1.42416919,
        -1.42426274, -1.42435727, -1.42445272, -1.42454905, -1.42464621,
        -1.42474415, -1.4248534 , -1.42497002, -1.42508716, -1.42520478,
        -1.42532286, -1.42544135, -1.42556023, -1.42572837, -1.42595237,
        -1.42617595, -1.42639911, -1.42662183, -1.42684409, -1.42706588,
        -1.42730915, -1.4275589 , -1.42780794, -1.42805626, -1.42830385,
        -1.4285507 , -1.42879681, -1.42904217, -1.42928677, -1.42953061,
        -1.42977368, -1.43001597, -1.43025749, -1.43052219, -1.43078855,
        -1.43109334, -1.43142155, -1.43174828, -1.43207352, -1.4323973 ,
        -1.43271961, -1.43304046, -1.43335987, -1.43367783, -1.43399436,
        -1.43430946, -1.43462315, -1.43493542, -1.43524629, -1.43555577]),
 'split7_test_score': array([-1.58358516, -1.5818867 , -1.58039288, -1.57905692, -1.57784835,
        -1.57674574, -1.57573317, -1.57479834, -1.57393144, -1.5731245 ,
        -1.57237089, -1.57172694, -1.57115959, -1.57072183, -1.5703258 ,
        -1.56995583, -1.56960987, -1.56928607, -1.56898278, -1.56869848,

Using the report function given below you can see the cv performance of top few models as well, that with the tentative performance

In [50]:
def report(results, n_top=3):
    for i in range(1, n_top + 1):
        candidates = np.flatnonzero(results['rank_test_score'] == i)
        for candidate in candidates:
            print("Model with rank: {0}".format(i))
            print("Mean validation score: {0:.3f} (std: {1:.3f})".format(
                  results['mean_test_score'][candidate],
                  results['std_test_score'][candidate]))
            print("Parameters: {0}".format(results['params'][candidate]))
            print("")

In [51]:
report(grid_search.cv_results_,100)

Model with rank: 1
Mean validation score: -1.611 (std: 0.117)
Parameters: {'alpha': 34.0}

Model with rank: 2
Mean validation score: -1.611 (std: 0.117)
Parameters: {'alpha': 35.0}

Model with rank: 3
Mean validation score: -1.611 (std: 0.117)
Parameters: {'alpha': 33.0}

Model with rank: 4
Mean validation score: -1.611 (std: 0.117)
Parameters: {'alpha': 36.0}

Model with rank: 5
Mean validation score: -1.611 (std: 0.117)
Parameters: {'alpha': 32.0}

Model with rank: 6
Mean validation score: -1.611 (std: 0.117)
Parameters: {'alpha': 37.0}

Model with rank: 7
Mean validation score: -1.611 (std: 0.117)
Parameters: {'alpha': 38.0}

Model with rank: 8
Mean validation score: -1.611 (std: 0.116)
Parameters: {'alpha': 31.0}

Model with rank: 9
Mean validation score: -1.611 (std: 0.117)
Parameters: {'alpha': 39.0}

Model with rank: 10
Mean validation score: -1.611 (std: 0.116)
Parameters: {'alpha': 30.0}

Model with rank: 11
Mean validation score: -1.611 (std: 0.117)
Parameters: {'alpha': 40.0}

Model with rank: 12
Mean validation score: -1.611 (std: 0.116)
Parameters: {'alpha': 29.0}

Model with rank: 13
Mean validation score: -1.611 (std: 0.117)
Parameters: {'alpha': 41.0}

Model with rank: 14
Mean validation score: -1.611 (std: 0.116)
Parameters: {'alpha': 28.0}

Model with rank: 15
Mean validation score: -1.611 (std: 0.117)
Parameters: {'alpha': 42.0}

Model with rank: 16
Mean validation score: -1.611 (std: 0.116)
Parameters: {'alpha': 27.0}

Model with rank: 17
Mean validation score: -1.611 (std: 0.118)
Parameters: {'alpha': 43.0}

Model with rank: 18
Mean validation score: -1.611 (std: 0.116)
Parameters: {'alpha': 26.0}

Model with rank: 19
Mean validation score: -1.611 (std: 0.118)
Parameters: {'alpha': 44.0}

Model with rank: 20
Mean validation score: -1.611 (std: 0.116)
Parameters: {'alpha': 25.0}

Model with rank: 21
Mean validation score: -1.611 (std: 0.118)
Parameters: {'alpha': 45.0}

Model with rank: 22
Mean validation score: -1.611 (std: 0.116)
Parameters: {'alpha': 24.0}

Model with rank: 23
Mean validation score: -1.612 (std: 0.118)
Parameters: {'alpha': 46.0}

Model with rank: 24
Mean validation score: -1.612 (std: 0.116)
Parameters: {'alpha': 23.0}

Model with rank: 25
Mean validation score: -1.612 (std: 0.118)
Parameters: {'alpha': 47.0}

Model with rank: 26
Mean validation score: -1.612 (std: 0.116)
Parameters: {'alpha': 22.0}

Model with rank: 27
Mean validation score: -1.612 (std: 0.118)
Parameters: {'alpha': 48.0}

Model with rank: 28
Mean validation score: -1.612 (std: 0.116)
Parameters: {'alpha': 21.0}

Model with rank: 29
Mean validation score: -1.612 (std: 0.118)
Parameters: {'alpha': 49.0}

Model with rank: 30
Mean validation score: -1.612 (std: 0.116)
Parameters: {'alpha': 20.0}

Model with rank: 31
Mean validation score: -1.612 (std: 0.118)
Parameters: {'alpha': 50.0}

Model with rank: 32
Mean validation score: -1.612 (std: 0.115)
Parameters: {'alpha': 19.0}

Model with rank: 33
Mean validation score: -1.612 (std: 0.118)
Parameters: {'alpha': 51.0}

Model with rank: 34
Mean validation score: -1.612 (std: 0.115)
Parameters: {'alpha': 18.0}

Model with rank: 35
Mean validation score: -1.612 (std: 0.118)
Parameters: {'alpha': 52.0}

Model with rank: 36
Mean validation score: -1.612 (std: 0.119)
Parameters: {'alpha': 53.0}

Model with rank: 37
Mean validation score: -1.612 (std: 0.115)
Parameters: {'alpha': 17.0}

Model with rank: 38
Mean validation score: -1.613 (std: 0.119)
Parameters: {'alpha': 54.0}

Model with rank: 39
Mean validation score: -1.613 (std: 0.115)
Parameters: {'alpha': 16.0}

Model with rank: 40
Mean validation score: -1.613 (std: 0.119)
Parameters: {'alpha': 55.0}

Model with rank: 41
Mean validation score: -1.613 (std: 0.115)
Parameters: {'alpha': 15.0}

Model with rank: 42
Mean validation score: -1.613 (std: 0.119)
Parameters: {'alpha': 56.0}

Model with rank: 43
Mean validation score: -1.613 (std: 0.119)
Parameters: {'alpha': 57.0}

Model with rank: 44
Mean validation score: -1.613 (std: 0.115)
Parameters: {'alpha': 14.0}

Model with rank: 45
Mean validation score: -1.613 (std: 0.119)
Parameters: {'alpha': 58.0}

Model with rank: 46
Mean validation score: -1.613 (std: 0.115)
Parameters: {'alpha': 13.0}

Model with rank: 47
Mean validation score: -1.613 (std: 0.119)
Parameters: {'alpha': 59.0}

Model with rank: 48
Mean validation score: -1.614 (std: 0.119)
Parameters: {'alpha': 60.0}

Model with rank: 49
Mean validation score: -1.614 (std: 0.115)
Parameters: {'alpha': 12.0}

Model with rank: 50
Mean validation score: -1.614 (std: 0.119)
Parameters: {'alpha': 61.0}

Model with rank: 51
Mean validation score: -1.614 (std: 0.119)
Parameters: {'alpha': 62.0}

Model with rank: 52
Mean validation score: -1.614 (std: 0.115)
Parameters: {'alpha': 11.0}

Model with rank: 53
Mean validation score: -1.614 (std: 0.120)
Parameters: {'alpha': 63.0}

Model with rank: 54
Mean validation score: -1.614 (std: 0.115)
Parameters: {'alpha': 10.0}

Model with rank: 55
Mean validation score: -1.614 (std: 0.120)
Parameters: {'alpha': 64.0}

Model with rank: 56
Mean validation score: -1.615 (std: 0.120)
Parameters: {'alpha': 65.0}

Model with rank: 57
Mean validation score: -1.615 (std: 0.115)
Parameters: {'alpha': 9.0}

Model with rank: 58
Mean validation score: -1.615 (std: 0.120)
Parameters: {'alpha': 66.0}

Model with rank: 59
Mean validation score: -1.615 (std: 0.120)
Parameters: {'alpha': 67.0}

Model with rank: 60
Mean validation score: -1.615 (std: 0.115)
Parameters: {'alpha': 8.0}

Model with rank: 61
Mean validation score: -1.615 (std: 0.120)
Parameters: {'alpha': 68.0}

Model with rank: 62
Mean validation score: -1.616 (std: 0.120)
Parameters: {'alpha': 69.0}

Model with rank: 63
Mean validation score: -1.616 (std: 0.115)
Parameters: {'alpha': 7.0}

Model with rank: 64
Mean validation score: -1.616 (std: 0.120)
Parameters: {'alpha': 70.0}

Model with rank: 65
Mean validation score: -1.616 (std: 0.120)
Parameters: {'alpha': 71.0}

Model with rank: 66
Mean validation score: -1.616 (std: 0.120)
Parameters: {'alpha': 72.0}

Model with rank: 67
Mean validation score: -1.616 (std: 0.115)
Parameters: {'alpha': 6.0}

Model with rank: 68
Mean validation score: -1.616 (std: 0.120)
Parameters: {'alpha': 73.0}

Model with rank: 69
Mean validation score: -1.617 (std: 0.121)
Parameters: {'alpha': 74.0}

Model with rank: 70
Mean validation score: -1.617 (std: 0.121)
Parameters: {'alpha': 75.0}

Model with rank: 71
Mean validation score: -1.617 (std: 0.115)
Parameters: {'alpha': 5.0}

Model with rank: 72
Mean validation score: -1.617 (std: 0.121)
Parameters: {'alpha': 76.0}

Model with rank: 73
Mean validation score: -1.617 (std: 0.121)
Parameters: {'alpha': 77.0}

Model with rank: 74
Mean validation score: -1.618 (std: 0.121)
Parameters: {'alpha': 78.0}

Model with rank: 75
Mean validation score: -1.618 (std: 0.115)
Parameters: {'alpha': 4.0}

Model with rank: 76
Mean validation score: -1.618 (std: 0.121)
Parameters: {'alpha': 79.0}

Model with rank: 77
Mean validation score: -1.618 (std: 0.121)
Parameters: {'alpha': 80.0}

Model with rank: 78
Mean validation score: -1.619 (std: 0.121)
Parameters: {'alpha': 81.0}

Model with rank: 79
Mean validation score: -1.619 (std: 0.115)
Parameters: {'alpha': 3.0}

Model with rank: 80
Mean validation score: -1.619 (std: 0.121)
Parameters: {'alpha': 82.0}

Model with rank: 81
Mean validation score: -1.619 (std: 0.121)
Parameters: {'alpha': 83.0}

Model with rank: 82
Mean validation score: -1.619 (std: 0.121)
Parameters: {'alpha': 84.0}

Model with rank: 83
Mean validation score: -1.620 (std: 0.115)
Parameters: {'alpha': 2.0}

Model with rank: 84
Mean validation score: -1.620 (std: 0.121)
Parameters: {'alpha': 85.0}

Model with rank: 85
Mean validation score: -1.620 (std: 0.121)
Parameters: {'alpha': 86.0}

Model with rank: 86
Mean validation score: -1.620 (std: 0.121)
Parameters: {'alpha': 87.0}

Model with rank: 87
Mean validation score: -1.620 (std: 0.122)
Parameters: {'alpha': 88.0}

Model with rank: 88
Mean validation score: -1.621 (std: 0.116)
Parameters: {'alpha': 1.0}

Model with rank: 89
Mean validation score: -1.621 (std: 0.122)
Parameters: {'alpha': 89.0}

Model with rank: 90
Mean validation score: -1.621 (std: 0.122)
Parameters: {'alpha': 90.0}

Model with rank: 91
Mean validation score: -1.621 (std: 0.122)
Parameters: {'alpha': 91.0}

Model with rank: 92
Mean validation score: -1.622 (std: 0.122)
Parameters: {'alpha': 92.0}

Model with rank: 93
Mean validation score: -1.622 (std: 0.122)
Parameters: {'alpha': 93.0}

Model with rank: 94
Mean validation score: -1.622 (std: 0.122)
Parameters: {'alpha': 94.0}

Model with rank: 95
Mean validation score: -1.622 (std: 0.122)
Parameters: {'alpha': 95.0}

Model with rank: 96
Mean validation score: -1.623 (std: 0.122)
Parameters: {'alpha': 96.0}

Model with rank: 97
Mean validation score: -1.623 (std: 0.122)
Parameters: {'alpha': 97.0}

Model with rank: 98
Mean validation score: -1.623 (std: 0.122)
Parameters: {'alpha': 98.0}

Model with rank: 99
Mean validation score: -1.624 (std: 0.122)
Parameters: {'alpha': 99.0}

Model with rank: 100
Mean validation score: -1.624 (std: 0.122)
Parameters: {'alpha': 100.0}

In [52]:
testDataPred_RidgeReg=grid_search.predict(test_df)

In [53]:
pd.DataFrame(testDataPred_RidgeReg).to_csv("Output_RidgeReg.csv",index=False)

# Lasso Regression

In [54]:
lambdas=np.linspace(1,10,100)
lasso_model=Lasso(fit_intercept=True)
lasso_param={'alpha':lambdas}

In [55]:
grid_search=GridSearchCV(lasso_model,param_grid=lasso_param,cv=10,scoring='neg_mean_absolute_error')

In [56]:
grid_search.fit(x_train,y_train)

GridSearchCV(cv=10, error_score='raise-deprecating',
             estimator=Lasso(alpha=1.0, copy_X=True, fit_intercept=True,
                             max_iter=1000, normalize=False, positive=False,
                             precompute=False, random_state=None,
                             selection='cyclic', tol=0.0001, warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'alpha': array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.5454...
        7.81818182,  7.90909091,  8.        ,  8.09090909,  8.18181818,
        8.27272727,  8.36363636,  8.45454545,  8.54545455,  8.63636364,
        8.72727273,  8.81818182,  8.90909091,  9.        ,  9.09090909,
        9.18181818,  9.27272727,  9.36363636,  9.45454545,  9.54545455,
        9.63636364,  9.72727273,  9.81818182,  9.90909091, 10.        ])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='neg_mean_absolute_error', verbose=0)

In [57]:
grid_search.best_estimator_

Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [58]:
lambdas=np.linspace(.001,2,100)
lasso_param={'alpha':lambdas}

In [59]:
grid_search=GridSearchCV(lasso_model,param_grid=lasso_param,cv=10,scoring='neg_mean_absolute_error')
grid_search.fit(x_train,y_train)

GridSearchCV(cv=10, error_score='raise-deprecating',
             estimator=Lasso(alpha=1.0, copy_X=True, fit_intercept=True,
                             max_iter=1000, normalize=False, positive=False,
                             precompute=False, random_state=None,
                             selection='cyclic', tol=0.0001, warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'alpha': array([1.00000000e-03, 2.11919192e-02, 4.13838384e-02, 6.15757576e-02,
       8.17...
       1.61635354e+00, 1.63654545e+00, 1.65673737e+00, 1.67692929e+00,
       1.69712121e+00, 1.71731313e+00, 1.73750505e+00, 1.75769697e+00,
       1.77788889e+00, 1.79808081e+00, 1.81827273e+00, 1.83846465e+00,
       1.85865657e+00, 1.87884848e+00, 1.89904040e+00, 1.91923232e+00,
       1.93942424e+00, 1.95961616e+00, 1.97980808e+00, 2.00000000e+00])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='neg_mean_absolute_error', verbose=0)

In [60]:
grid_search.best_estimator_

Lasso(alpha=0.021191919191919192, copy_X=True, fit_intercept=True,
      max_iter=1000, normalize=False, positive=False, precompute=False,
      random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

In [61]:
report(grid_search.cv_results_,5)

Model with rank: 1
Mean validation score: -1.603 (std: 0.120)
Parameters: {'alpha': 0.021191919191919192}

Model with rank: 2
Mean validation score: -1.612 (std: 0.126)
Parameters: {'alpha': 0.041383838383838384}

Model with rank: 3
Mean validation score: -1.617 (std: 0.115)
Parameters: {'alpha': 0.001}

Model with rank: 4
Mean validation score: -1.619 (std: 0.127)
Parameters: {'alpha': 0.061575757575757575}

Model with rank: 5
Mean validation score: -1.624 (std: 0.128)
Parameters: {'alpha': 0.08176767676767677}

In [62]:
lasso_model=grid_search.best_estimator_

In [63]:
lasso_model.fit(x_train,y_train)

Lasso(alpha=0.021191919191919192, copy_X=True, fit_intercept=True,
      max_iter=1000, normalize=False, positive=False, precompute=False,
      random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

In [64]:
x_train2=train2.drop('Interest.Rate',axis=1)
predicted_value_LassoReg = lasso_model.predict(x_train2)
r2_score(train2['Interest.Rate'],predicted_value_LassoReg)

0.7683529322767257

In [65]:
list(zip(x_train.columns,lasso_model.coef_))

[('Amount.Requested', 0.00016025576388069374),
 ('Debt.To.Income.Ratio', -0.0009940455335086431),
 ('Monthly.Income', -2.7161150694601474e-05),
 ('Open.CREDIT.Lines', -0.03776066942268258),
 ('Revolving.CREDIT.Balance', -3.2291582902347866e-06),
 ('Inquiries.in.the.Last.6.Months', 0.32734647665538585),
 ('Employment.Length', 0.011883001638602755),
 ('FICO.Score', -0.08647817945138424),
 ('Loan.Length_36 months', -3.0098932744846625),
 ('Loan.Purpose_debt_consolidation', -0.1780182230425123),
 ('Loan.Purpose_credit_card', -0.22053269213383622),
 ('Loan.Purpose_other', 0.3196217853383159),
 ('Loan.Purpose_home_improvement', -0.0),
 ('Loan.Purpose_major_purchase', 0.0),
 ('Loan.Purpose_small_business', 0.0),
 ('Loan.Purpose_car', 0.0),
 ('Loan.Purpose_wedding', -0.0),
 ('Loan.Purpose_medical', -0.0),
 ('Loan.Purpose_moving', 0.0),
 ('State_CA', -0.0),
 ('State_NY', 0.0),
 ('State_TX', 0.2592516325019152),
 ('State_FL', 0.0),
 ('State_IL', -0.0),
 ('State_GA', -0.0),
 ('State_PA', -0.0),
 ('State_NJ', -0.0),
 ('State_VA', 0.0),
 ('State_MA', 0.0),
 ('State_OH', -0.0),
 ('State_MD', 0.0),
 ('State_NC', -0.0),
 ('State_CO', 0.0),
 ('State_WA', -0.0),
 ('State_CT', 0.0),
 ('State_AZ', 0.0),
 ('State_MI', 0.0),
 ('State_AL', 0.0),
 ('State_MN', -0.0),
 ('State_MO', -0.0),
 ('State_NV', 0.0),
 ('State_OR', 0.0),
 ('State_SC', 0.0),
 ('State_WI', 0.0),
 ('State_KY', 0.0),
 ('State_LA', 0.0),
 ('State_KS', 0.0),
 ('Home.Ownership_MORTGAGE', -0.15598777750113385),
 ('Home.Ownership_RENT', 0.0)]

In [66]:
testDataPred_LassoReg=grid_search.predict(test_df)

In [67]:
pd.DataFrame(testDataPred_LassoReg).to_csv("Output_LassoReg.csv",index=False)